CREATE TABLE users (
  id         UUID PRIMARY KEY NOT NULL, -- REFERENCES auth.users(id) ON DELETE CASCADE

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;